# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './uvvino.ui'
#
# Created: Mon Oct 14 12:25:11 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UVVino(object):
    def setupUi(self, UVVino):
        UVVino.setObjectName(_fromUtf8("UVVino"))
        UVVino.resize(1113, 864)
        UVVino.setStatusTip(_fromUtf8(""))
        UVVino.setWhatsThis(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(UVVino)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.startstop_button = QtGui.QPushButton(self.centralwidget)
        self.startstop_button.setGeometry(QtCore.QRect(1000, 735, 92, 27))
        self.startstop_button.setObjectName(_fromUtf8("startstop_button"))
        self.time_set = QtGui.QSpinBox(self.centralwidget)
        self.time_set.setGeometry(QtCore.QRect(900, 735, 51, 24))
        self.time_set.setMaximum(999)
        self.time_set.setSingleStep(1)
        self.time_set.setProperty("value", 20)
        self.time_set.setObjectName(_fromUtf8("time_set"))
        self.rangegroupbox = QtGui.QGroupBox(self.centralwidget)
        self.rangegroupbox.setGeometry(QtCore.QRect(50, 710, 411, 51))
        self.rangegroupbox.setObjectName(_fromUtf8("rangegroupbox"))
        self.radio_AU = QtGui.QRadioButton(self.rangegroupbox)
        self.radio_AU.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.radio_AU.setObjectName(_fromUtf8("radio_AU"))
        self.radio_mau = QtGui.QRadioButton(self.rangegroupbox)
        self.radio_mau.setEnabled(True)
        self.radio_mau.setGeometry(QtCore.QRect(90, 20, 121, 20))
        self.radio_mau.setChecked(False)
        self.radio_mau.setObjectName(_fromUtf8("radio_mau"))
        self.radio_mv = QtGui.QRadioButton(self.rangegroupbox)
        self.radio_mv.setGeometry(QtCore.QRect(220, 20, 71, 20))
        self.radio_mv.setObjectName(_fromUtf8("radio_mv"))
        self.radio_raw = QtGui.QRadioButton(self.rangegroupbox)
        self.radio_raw.setGeometry(QtCore.QRect(310, 20, 51, 20))
        self.radio_raw.setChecked(True)
        self.radio_raw.setObjectName(_fromUtf8("radio_raw"))
        self.lcd = QtGui.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(970, 0, 131, 31))
        self.lcd.setObjectName(_fromUtf8("lcd"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(640, 730, 191, 31))
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(840, 740, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(960, 740, 31, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.valve_a = QtGui.QSpinBox(self.centralwidget)
        self.valve_a.setGeometry(QtCore.QRect(110, 770, 55, 25))
        self.valve_a.setReadOnly(False)
        self.valve_a.setMaximum(100)
        self.valve_a.setSingleStep(10)
        self.valve_a.setProperty("value", 100)
        self.valve_a.setObjectName(_fromUtf8("valve_a"))
        self.valve_b = QtGui.QSpinBox(self.centralwidget)
        self.valve_b.setGeometry(QtCore.QRect(290, 770, 55, 25))
        self.valve_b.setMaximum(100)
        self.valve_b.setSingleStep(10)
        self.valve_b.setObjectName(_fromUtf8("valve_b"))
        self.valve_c = QtGui.QSpinBox(self.centralwidget)
        self.valve_c.setGeometry(QtCore.QRect(460, 770, 55, 25))
        self.valve_c.setMaximum(100)
        self.valve_c.setSingleStep(10)
        self.valve_c.setObjectName(_fromUtf8("valve_c"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 770, 91, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 770, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 770, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 770, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.valvetime = QtGui.QSpinBox(self.centralwidget)
        self.valvetime.setGeometry(QtCore.QRect(590, 770, 51, 24))
        self.valvetime.setMaximum(999)
        self.valvetime.setSingleStep(1)
        self.valvetime.setProperty("value", 0)
        self.valvetime.setObjectName(_fromUtf8("valvetime"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(650, 770, 51, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.mixing_addbutton = QtGui.QPushButton(self.centralwidget)
        self.mixing_addbutton.setGeometry(QtCore.QRect(800, 770, 51, 27))
        self.mixing_addbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mixing_addbutton.setObjectName(_fromUtf8("mixing_addbutton"))
        self.mixing_grad_check = QtGui.QCheckBox(self.centralwidget)
        self.mixing_grad_check.setGeometry(QtCore.QRect(690, 770, 91, 20))
        self.mixing_grad_check.setChecked(True)
        self.mixing_grad_check.setObjectName(_fromUtf8("mixing_grad_check"))
        self.valve_a_button = QtGui.QPushButton(self.centralwidget)
        self.valve_a_button.setGeometry(QtCore.QRect(10, 790, 51, 27))
        self.valve_a_button.setObjectName(_fromUtf8("valve_a_button"))
        self.valve_b_button = QtGui.QPushButton(self.centralwidget)
        self.valve_b_button.setGeometry(QtCore.QRect(180, 790, 51, 27))
        self.valve_b_button.setObjectName(_fromUtf8("valve_b_button"))
        self.valve_c_button = QtGui.QPushButton(self.centralwidget)
        self.valve_c_button.setGeometry(QtCore.QRect(360, 790, 51, 27))
        self.valve_c_button.setObjectName(_fromUtf8("valve_c_button"))
        UVVino.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(UVVino)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        UVVino.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(UVVino)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(UVVino)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))

        self.retranslateUi(UVVino)
        QtCore.QMetaObject.connectSlotsByName(UVVino)

    def retranslateUi(self, UVVino):
        UVVino.setWindowTitle(_translate("UVVino", "UV/Vino", None))
        self.startstop_button.setToolTip(_translate("UVVino", "Start/Stop the data collecting", None))
        self.startstop_button.setText(_translate("UVVino", "Initialize", None))
        self.time_set.setToolTip(_translate("UVVino", "Set the runtime in minutes", None))
        self.rangegroupbox.setTitle(_translate("UVVino", "Range:", None))
        self.radio_AU.setToolTip(_translate("UVVino", "AU", None))
        self.radio_AU.setText(_translate("UVVino", "0-1 AU", None))
        self.radio_mau.setToolTip(_translate("UVVino", "mAU", None))
        self.radio_mau.setText(_translate("UVVino", "0 - 1000 mAU", None))
        self.radio_mv.setToolTip(_translate("UVVino", "uVolt", None))
        self.radio_mv.setText(_translate("UVVino", "miliVolt", None))
        self.radio_raw.setToolTip(_translate("UVVino", "RAW", None))
        self.radio_raw.setText(_translate("UVVino", "RAW", None))
        self.lineEdit.setText(_translate("UVVino", "/dev/ttyUSB0", None))
        self.label.setText(_translate("UVVino", "Runtime:", None))
        self.label_2.setText(_translate("UVVino", "min", None))
        self.label_4.setText(_translate("UVVino", "Valve B (%):", None))
        self.label_6.setText(_translate("UVVino", "Valve A (%):", None))
        self.label_5.setText(_translate("UVVino", "Valve C (%):", None))
        self.label_3.setText(_translate("UVVino", "@Time:", None))
        self.valvetime.setToolTip(_translate("UVVino", "Set the runtime in minutes", None))
        self.label_7.setText(_translate("UVVino", "min", None))
        self.mixing_addbutton.setText(_translate("UVVino", "Add", None))
        self.mixing_grad_check.setText(_translate("UVVino", "Gradient", None))
        self.valve_a_button.setText(_translate("UVVino", "Open", None))
        self.valve_b_button.setText(_translate("UVVino", "Open", None))
        self.valve_c_button.setText(_translate("UVVino", "Open", None))
        self.actionSave.setText(_translate("UVVino", "Save As", None))
        self.actionExit.setText(_translate("UVVino", "Exit", None))

